In [2]:
import pandas as pd
df = pd.read_csv('Resume/Resume.csv')

In [3]:
df.head(100)

,ID,Resume_str,Resume_html,Category
0,16852973,HR ADMINISTRATOR/MARKETING ASSOCIATE\...,"<div class=""fontsize fontface vmargins hmargin...",HR
1,22323967,"HR SPECIALIST, US HR OPERATIONS ...","<div class=""fontsize fontface vmargins hmargin...",HR
2,33176873,HR DIRECTOR Summary Over 2...,"<div class=""fontsize fontface vmargins hmargin...",HR
3,27018550,HR SPECIALIST Summary Dedica...,"<div class=""fontsize fontface vmargins hmargin...",HR
4,17812897,HR MANAGER Skill Highlights ...,"<div class=""fontsize fontface vmargins hmargin...",HR
...,...,...,...,...
95,28640735,DIRECTOR OF HR Executive Pr...,"<div class=""fontsize fontface vmargins hmargin...",HR
96,15575117,HR SENIOR SPECIALIST Career Ove...,"<div class=""fontsize fontface vmargins hmargin...",HR
97,27496514,HR CUSTOMER SERVICE REPRESENTATIVE ...,"<div class=""fontsize fontface vmargins hmargin...",HR
98,14256329,HR SERVICES REPRESENTATIVE Summ...,"<div class=""fontsize fontface vmargins hmargin...",HR
99,19336728,HR ASSISTANT INTERN Summary ...,"<div class=""fontsize fontface vmargins hmargin...",HR

In [4]:
# Filter the DataFrame
df = df[df['Category'].isin(['HR', 'INFORMATION-TECHNOLOGY'])]

# Verify the results
print(df['Category'].unique())

['HR' 'INFORMATION-TECHNOLOGY']

In [6]:
df

,ID,Resume_str,Resume_html,Category
0,16852973,HR ADMINISTRATOR/MARKETING ASSOCIATE\...,"<div class=""fontsize fontface vmargins hmargin...",HR
1,22323967,"HR SPECIALIST, US HR OPERATIONS ...","<div class=""fontsize fontface vmargins hmargin...",HR
2,33176873,HR DIRECTOR Summary Over 2...,"<div class=""fontsize fontface vmargins hmargin...",HR
3,27018550,HR SPECIALIST Summary Dedica...,"<div class=""fontsize fontface vmargins hmargin...",HR
4,17812897,HR MANAGER Skill Highlights ...,"<div class=""fontsize fontface vmargins hmargin...",HR
...,...,...,...,...
332,27485716,CORPORATE PROJECT MANAGER Caree...,"<div class=""fontsize fontface vmargins hmargin...",INFORMATION-TECHNOLOGY
333,26480367,IT TECHNOLOGY SPECIALIST Profes...,"<div class=""fontsize fontface vmargins hmargin...",INFORMATION-TECHNOLOGY
334,81761658,IT MANAGER Highlights ...,"<div class=""fontsize fontface vmargins hmargin...",INFORMATION-TECHNOLOGY
335,79541391,SUBJECT MATTER EXPERT (INFORMATION TE...,"<div class=""fontsize fontface vmargins hmargin...",INFORMATION-TECHNOLOGY
336,23666211,TRAINING MANAGER Executive Su...,"<div class=""fontsize fontface vmargins hmargin...",INFORMATION-TECHNOLOGY

In [7]:
df.to_csv('Resume/Resume.csv', index=False)

In [8]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 230 entries, 0 to 336
Data columns (total 4 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   ID           230 non-null    int64
 1   Resume_str   230 non-null    object
 2   Resume_html  230 non-null    object
 3   Category     230 non-null    object
dtypes: int64(1), object(3)
memory usage: 9.0+ KB